project:
  type: website

website:
  title: "Learning at The Data Thread, January 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01-part-1.qmd
        text: Part 1
      - href: 02-part-2.qmd
        text: Part 2
      - href: 03-part-3.qmd
        text: Part 3
      - href: 04-part-4.qmd
        text: Part 4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



